/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as EodRouteImport } from './routes/eod'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as PoaRouteImport } from './routes/poa'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as TrainersRouteImport } from './routes/trainers'
import { Route as TrainingBatchesRouteImport } from './routes/training-batches'
import { Route as TrainingRequestsRouteImport } from './routes/training-requests'
import { Route as ModulesModuleRouteImport } from './routes/modules.$module'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const EodRoute = EodRouteImport.update({
  id: '/eod',
  path: '/eod',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const PoaRoute = PoaRouteImport.update({
  id: '/poa',
  path: '/poa',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainersRoute = TrainersRouteImport.update({
  id: '/trainers',
  path: '/trainers',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingBatchesRoute = TrainingBatchesRouteImport.update({
  id: '/training-batches',
  path: '/training-batches',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRequestsRoute = TrainingRequestsRouteImport.update({
  id: '/training-requests',
  path: '/training-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesModuleRoute = ModulesModuleRouteImport.update({
  id: '/modules/$module',
  path: '/modules/$module',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/calls': typeof CallsRoute
  '/contacts': typeof ContactsRoute
  '/deals': typeof DealsRoute
  '/eod': typeof EodRoute
  '/leads': typeof LeadsRoute
  '/meetings': typeof MeetingsRoute
  '/poa': typeof PoaRoute
  '/tasks': typeof TasksRoute
  '/trainers': typeof TrainersRoute
  '/training-batches': typeof TrainingBatchesRoute
  '/training-requests': typeof TrainingRequestsRoute
  '/modules/$module': typeof ModulesModuleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/calls': typeof CallsRoute
  '/contacts': typeof ContactsRoute
  '/deals': typeof DealsRoute
  '/eod': typeof EodRoute
  '/leads': typeof LeadsRoute
  '/meetings': typeof MeetingsRoute
  '/poa': typeof PoaRoute
  '/tasks': typeof TasksRoute
  '/trainers': typeof TrainersRoute
  '/training-batches': typeof TrainingBatchesRoute
  '/training-requests': typeof TrainingRequestsRoute
  '/modules/$module': typeof ModulesModuleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/calls': typeof CallsRoute
  '/contacts': typeof ContactsRoute
  '/deals': typeof DealsRoute
  '/eod': typeof EodRoute
  '/leads': typeof LeadsRoute
  '/meetings': typeof MeetingsRoute
  '/poa': typeof PoaRoute
  '/tasks': typeof TasksRoute
  '/trainers': typeof TrainersRoute
  '/training-batches': typeof TrainingBatchesRoute
  '/training-requests': typeof TrainingRequestsRoute
  '/modules/$module': typeof ModulesModuleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/calls'
    | '/contacts'
    | '/deals'
    | '/eod'
    | '/leads'
    | '/meetings'
    | '/poa'
    | '/tasks'
    | '/trainers'
    | '/training-batches'
    | '/training-requests'
    | '/modules/$module'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/calls'
    | '/contacts'
    | '/deals'
    | '/eod'
    | '/leads'
    | '/meetings'
    | '/poa'
    | '/tasks'
    | '/trainers'
    | '/training-batches'
    | '/training-requests'
    | '/modules/$module'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/calls'
    | '/contacts'
    | '/deals'
    | '/eod'
    | '/leads'
    | '/meetings'
    | '/poa'
    | '/tasks'
    | '/trainers'
    | '/training-batches'
    | '/training-requests'
    | '/modules/$module'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  CallsRoute: typeof CallsRoute
  ContactsRoute: typeof ContactsRoute
  DealsRoute: typeof DealsRoute
  EodRoute: typeof EodRoute
  LeadsRoute: typeof LeadsRoute
  MeetingsRoute: typeof MeetingsRoute
  PoaRoute: typeof PoaRoute
  TasksRoute: typeof TasksRoute
  TrainersRoute: typeof TrainersRoute
  TrainingBatchesRoute: typeof TrainingBatchesRoute
  TrainingRequestsRoute: typeof TrainingRequestsRoute
  ModulesModuleRoute: typeof ModulesModuleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eod': {
      id: '/eod'
      path: '/eod'
      fullPath: '/eod'
      preLoaderRoute: typeof EodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poa': {
      id: '/poa'
      path: '/poa'
      fullPath: '/poa'
      preLoaderRoute: typeof PoaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainers': {
      id: '/trainers'
      path: '/trainers'
      fullPath: '/trainers'
      preLoaderRoute: typeof TrainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training-batches': {
      id: '/training-batches'
      path: '/training-batches'
      fullPath: '/training-batches'
      preLoaderRoute: typeof TrainingBatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training-requests': {
      id: '/training-requests'
      path: '/training-requests'
      fullPath: '/training-requests'
      preLoaderRoute: typeof TrainingRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/$module': {
      id: '/modules/$module'
      path: '/modules/$module'
      fullPath: '/modules/$module'
      preLoaderRoute: typeof ModulesModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  CallsRoute: CallsRoute,
  ContactsRoute: ContactsRoute,
  DealsRoute: DealsRoute,
  EodRoute: EodRoute,
  LeadsRoute: LeadsRoute,
  MeetingsRoute: MeetingsRoute,
  PoaRoute: PoaRoute,
  TasksRoute: TasksRoute,
  TrainersRoute: TrainersRoute,
  TrainingBatchesRoute: TrainingBatchesRoute,
  TrainingRequestsRoute: TrainingRequestsRoute,
  ModulesModuleRoute: ModulesModuleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
